# Generated by Django 4.2.5 on 2023-09-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tzmodels', '0006_remove_lessonview_viewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='viewed',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='viewedTime',
        ),
        migrations.AddField(
            model_name='lessonview',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonview',
            name='viewedTime',
            field=models.IntegerField(default=0),
        ),
    ]
