# Generated by Django 4.2.5 on 2023-09-25 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tzmodels', '0007_remove_lesson_viewed_remove_lesson_viewedtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hasAccess',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
