# Generated by Django 4.2.5 on 2023-09-25 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tzmodels', '0011_lessonview_inproduct_alter_lessonview_lastview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonview',
            name='inProduct',
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='lastView',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 22, 22, 18, 883611, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.SmallIntegerField(),
        ),
    ]
