# Generated by Django 4.2.5 on 2023-09-25 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tzmodels', '0012_remove_lessonview_inproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='lastView',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 22, 23, 3, 3720, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product', max_length=200),
        ),
    ]
