# Generated by Django 4.2.5 on 2023-09-26 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tzmodels', '0014_alter_lessonview_lastview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='lastView',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 18, 32, 47, 621171, tzinfo=datetime.timezone.utc)),
        ),
    ]
